export const DRAGGABLE_ID = {
  COLUMN: "COLUMN",
};

export const DROPPABLE_ID = {
  CANVAS_MAIN: "CANVAS_MAIN",
  X_AXIS_WELL: "X_AXIS_WELL",
  Y_AXIS_WELL: "Y_AXIS_WELL",

  PIVOT_COLUMNS_WELL: "PIVOT_COLUMNS_WELL",
  PIVOT_ROWS_WELL: "PIVOT_ROWS_WELL",
  PIVOT_VALUES_WELL: "PUVOT_VALUES_WELL",
};
